### PR TITLE
Support 1.17 and Java 16

### PR DESCRIPTION
**Pull request by Primorior**
Libraries probably need updates too

### CODE REVIEW

**Comment by Primorior** [comment]
Forgot the Java 16 update in the dependency-reduced-pom, needs update too

**Comment by rhystedstone** [comment]
Dependencies such as NBTAPI and XSeries will probably break also. Idk who thought it was a good idea to have dependencies refuse to work if outdated.

**Comment by ghost** [comment]
> XSeries

yeah these need to be updated for sure. They are pretty much the only things that need to be updated when new versions come out, without it I doubt this pull request will work as desired

**Comment by ghost** [comment]
Ill merge this, update the libs and test the plugin

**Pull request merged**
